use anyhow::Result;
use ethers::providers::{Provider, Http, Middleware};
use ethers::types::{Block, H256, U64};
use std::sync::Arc;
use tokio::sync::RwLock;
use tracing::{info, warn};

use crate::fork_detector::ForkDetector;
use crate::metrics::Metrics;

pub struct BlockchainMonitor {
    provider: Provider<Http>,
        metrics: Arc<Metrics>,
            fork_detector: Arc<RwLock<ForkDetector>>,
                last_block: Arc<RwLock<Option<U64>>>,
                }

                impl BlockchainMonitor {
                    pub fn new(provider: Provider<Http>, metrics: Arc<Metrics>) -> Self {
                            Self {
                                        provider,
                                                    metrics,
                                                                fork_detector: Arc::new(RwLock::new(ForkDetector::new(100))),
                                                                            last_block: Arc::new(RwLock::new(None)),
                                                                                    }
                                                                                        }

                                                                                            pub async fn poll(&self) -> Result<()> {
                                                                                                    let current_block = self.provider.get_block_number().await?;
                                                                                                            
                                                                                                                    // Update block height metric
                                                                                                                            self.metrics.set_block_height(current_block.as_u64());

                                                                                                                                    let mut last_block = self.last_block.write().await;
                                                                                                                                            
                                                                                                                                                    // Check if we missed blocks (reorg or restart)
                                                                                                                                                            if let Some(prev_block) = *last_block {
                                                                                                                                                                        if current_block > prev_block + 1 {
                                                                                                                                                                                        warn!("Missed {} blocks", current_block - prev_block - 1);
                                                                                                                                                                                                        self.metrics.increment_missed_blocks((current_block - prev_block - 1).as_u64());
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                    // Fetch the block
                                                                                                                                                                                                                                            if let Some(block) = self.provider.get_block(current_block).await? {
                                                                                                                                                                                                                                                        self.process_block(block).await?;
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                        *last_block = Some(current_block);
                                                                                                                                                                                                                                                                                Ok(())
                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                        async fn process_block(&self, block: Block<H256>) -> Result<()> {
                                                                                                                                                                                                                                                                                                let block_number = block.number.unwrap().as_u64();
                                                                                                                                                                                                                                                                                                        let block_hash = block.hash.unwrap();
                                                                                                                                                                                                                                                                                                                let parent_hash = block.parent_hash;
                                                                                                                                                                                                                                                                                                                        let timestamp = block.timestamp.as_u64();
                                                                                                                                                                                                                                                                                                                                let difficulty = block.difficulty;
                                                                                                                                                                                                                                                                                                                                        let gas_used = block.gas_used.as_u64();
                                                                                                                                                                                                                                                                                                                                                let gas_limit = block.gas_limit.as_u64();
                                                                                                                                                                                                                                                                                                                                                        let tx_count = block.transactions.len() as u64;

                                                                                                                                                                                                                                                                                                                                                                // Update basic metrics
                                                                                                                                                                                                                                                                                                                                                                        self.metrics.set_block_timestamp(timestamp);
                                                                                                                                                                                                                                                                                                                                                                                self.metrics.set_block_gas_used(gas_used);
                                                                                                                                                                                                                                                                                                                                                                                        self.metrics.set_block_gas_limit(gas_limit);
                                                                                                                                                                                                                                                                                                                                                                                                self.metrics.set_transaction_count(tx_count);
                                                                                                                                                                                                                                                                                                                                                                                                        self.metrics.observe_block_difficulty(difficulty.as_u128() as f64);

                                                                                                                                                                                                                                                                                                                                                                                                                // Calculate block time
                                                                                                                                                                                                                                                                                                                                                                                                                        if block_number > 0 {
                                                                                                                                                                                                                                                                                                                                                                                                                                    if let Some(parent) = self.provider.get_block(block_number - 1).await? {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    let block_time = timestamp - parent.timestamp.as_u64();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.metrics.observe_block_time(block_time as f64);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Check for forks
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let mut fork_detector = self.fork_detector.write().await;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if let Some(fork_info) = fork_detector.add_block(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            block_number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        block_hash,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    parent_hash,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        warn!(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Fork detected at height {}: depth={}, competing_blocks={}",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fork_info.height, fork_info.depth, fork_info.competing_blocks
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.metrics.increment_fork_count();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.metrics.observe_fork_depth(fork_info.depth as f64);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.metrics.set_active_forks(fork_info.active_forks as i64);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    info!(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Block {}: {} txs, {} gas, {} difficulty",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            block_number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tx_count,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gas_used,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                difficulty
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Ok(())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    