use prometheus::{
        Counter, Histogram, HistogramOpts, IntCounter, IntGauge, Opts, Registry,
        };

        pub struct Metrics {
            pub registry: Registry,
                
                    // Block metrics
                        block_height: IntGauge,
                            block_timestamp: IntGauge,
                                block_gas_used: IntGauge,
                                    block_gas_limit: IntGauge,
                                        block_time: Histogram,
                                            block_difficulty: Histogram,
                                                
                                                    // Transaction metrics
                                                        transaction_count: IntGauge,
                                                            
                                                                // Fork metrics
                                                                    fork_count: IntCounter,
                                                                        fork_depth: Histogram,
                                                                            active_forks: IntGauge,
                                                                                missed_blocks: IntCounter,
                                                                                }

                                                                                impl Metrics {
                                                                                    pub fn new() -> Self {
                                                                                            let registry = Registry::new();

                                                                                                    let block_height = IntGauge::with_opts(
                                                                                                                Opts::new("mordor_block_height", "Current block height")
                                                                                                                                .namespace("etc"),
                                                                                                                                        ).unwrap();

                                                                                                                                                let block_timestamp = IntGauge::with_opts(
                                                                                                                                                            Opts::new("mordor_block_timestamp", "Block timestamp")
                                                                                                                                                                            .namespace("etc"),
                                                                                                                                                                                    ).unwrap();

                                                                                                                                                                                            let block_gas_used = IntGauge::with_opts(
                                                                                                                                                                                                        Opts::new("mordor_block_gas_used", "Gas used in current block")
                                                                                                                                                                                                                        .namespace("etc"),
                                                                                                                                                                                                                                ).unwrap();

                                                                                                                                                                                                                                        let block_gas_limit = IntGauge::with_opts(
                                                                                                                                                                                                                                                    Opts::new("mordor_block_gas_limit", "Block gas limit")
                                                                                                                                                                                                                                                                    .namespace("etc"),
                                                                                                                                                                                                                                                                            ).unwrap();

                                                                                                                                                                                                                                                                                    let block_time = Histogram::with_opts(
                                                                                                                                                                                                                                                                                                HistogramOpts::new("mordor_block_time_seconds", "Time between blocks")
                                                                                                                                                                                                                                                                                                                .namespace("etc")
                                                                                                                                                                                                                                                                                                                                .buckets(vec![1.0, 5.0, 10.0, 13.0, 15.0, 20.0, 30.0, 60.0]),
                                                                                                                                                                                                                                                                                                                                        ).unwrap();

                                                                                                                                                                                                                                                                                                                                                let block_difficulty = Histogram::with_opts(
                                                                                                                                                                                                                                                                                                                                                            HistogramOpts::new("mordor_block_difficulty", "Block difficulty")
                                                                                                                                                                                                                                                                                                                                                                            .namespace("etc")
                                                                                                                                                                                                                                                                                                                                                                                            .buckets(prometheus::exponential_buckets(1e9, 2.0, 20).unwrap()),
                                                                                                                                                                                                                                                                                                                                                                                                    ).unwrap();

                                                                                                                                                                                                                                                                                                                                                                                                            let transaction_count = IntGauge::with_opts(
                                                                                                                                                                                                                                                                                                                                                                                                                        Opts::new("mordor_transaction_count", "Transactions in current block")
                                                                                                                                                                                                                                                                                                                                                                                                                                        .namespace("etc"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                ).unwrap();

                                                                                                                                                                                                                                                                                                                                                                                                                                                        let fork_count = IntCounter::with_opts(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Opts::new("mordor_fork_total", "Total number of forks detected")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .namespace("etc"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ).unwrap();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let fork_depth = Histogram::with_opts(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                HistogramOpts::new("mordor_fork_depth", "Fork reorganization depth")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .namespace("etc")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .buckets(vec![1.0, 2.0, 5.0, 10.0, 50.0, 100.0, 500.0, 1000.0]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ).unwrap();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let active_forks = IntGauge::with_opts(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Opts::new("mordor_active_forks", "Number of currently active forks")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .namespace("etc"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ).unwrap();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let missed_blocks = IntCounter::with_opts(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Opts::new("mordor_missed_blocks_total", "Total missed blocks")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .namespace("etc"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ).unwrap();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Register all metrics
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                registry.register(Box::new(block_height.clone())).unwrap();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        registry.register(Box::new(block_timestamp.clone())).unwrap();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                registry.register(Box::new(block_gas_used.clone())).unwrap();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        registry.register(Box::new(block_gas_limit.clone())).unwrap();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                registry.register(Box::new(block_time.clone())).unwrap();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        registry.register(Box::new(block_difficulty.clone())).unwrap();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                registry.register(Box::new(transaction_count.clone())).unwrap();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        registry.register(Box::new(fork_count.clone())).unwrap();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                registry.register(Box::new(fork_depth.clone())).unwrap();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        registry.register(Box::new(active_forks.clone())).unwrap();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                registry.register(Box::new(missed_blocks.clone())).unwrap();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Self {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    registry,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                block_height,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            block_timestamp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        block_gas_used,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    block_gas_limit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                block_time,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            block_difficulty,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        transaction_count,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fork_count,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fork_depth,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            active_forks,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        missed_blocks,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub fn set_block_height(&self, height: u64) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.block_height.set(height as i64);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub fn set_block_timestamp(&self, timestamp: u64) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.block_timestamp.set(timestamp as i64);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub fn set_block_gas_used(&self, gas: u64) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.block_gas_used.set(gas as i64);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub fn set_block_gas_limit(&self, limit: u64) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.block_gas_limit.set(limit as i64);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub fn observe_block_time(&self, seconds: f64) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.block_time.observe(seconds);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub fn observe_block_difficulty(&self, difficulty: f64) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.block_difficulty.observe(difficulty);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub fn set_transaction_count(&self, count: u64) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.transaction_count.set(count as i64);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub fn increment_fork_count(&self) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.fork_count.inc();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub fn observe_fork_depth(&self, depth: f64) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.fork_depth.observe(depth);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub fn set_active_forks(&self, count: i64) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.active_forks.set(count);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pub fn increment_missed_blocks(&self, count: u64) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.missed_blocks.inc_by(count);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
}